TEXDIR /texlive
TEXMFSYSVAR /texlive/texmf-var
TEXMFSYSCONFIG /texlive/texmf-config
TEXMFLOCAL /texlive/texmf-local
TEXMFHOME $TEXMFLOCAL
TEXMFVAR $TEXMFSYSVAR
TEXMFCONFIG $TEXMFSYSCONFIG
collection-latex 1
collection-latexextra 1
collection-luatex 1
collection-fontsrecommended 1
option_doc 0
option_src 0
portable 1
